import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * The last five changes to this page, from git.
 *
 * A portfolio is a claim about the present tense that goes stale the day it is
 * published, and a reader has no way to tell a page shipped last week from one
 * shipped last year. Five dated lines answer that without anyone maintaining a
 * changelog by hand, and they give a second conversation something specific to
 * be about, which "just following up" never is.
 *
 * Subjects are truncated rather than reformatted. A commit message written for
 * the log is the honest artifact; rewriting it for display would turn this back
 * into the hand-maintained thing it exists to replace. Falls back to an empty
 * list outside a git checkout, which is what a deploy from a tarball looks like.
 */
let entries: { date: string; subject: string }[] = [];

try {
  const log = execFileSync("git", ["log", "-5", "--date=short", "--pretty=%ad|%s"], {
    encoding: "utf8",
    cwd: process.cwd(),
    stdio: ["ignore", "pipe", "ignore"],
  });

  entries = log
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      // Split on the first separator only. Splitting on whitespace kept the
      // first word of the subject and silently dropped the rest.
      const at = line.indexOf("|");
      return { date: line.slice(0, at), subject: line.slice(at + 1).slice(0, 96) };
    })
    .filter((e) => e.date && e.subject);
} catch {
  // Not a git checkout, or git is unavailable. The footer renders without this.
}

writeFileSync(
  join(process.cwd(), "lib/changelog.json"),
  JSON.stringify(
    { note: "Generated by scripts/build-changelog.ts from git log. Do not edit by hand.", entries },
    null,
    2,
  ) + "\n",
);

console.log(`build-changelog: ${entries.length} entries`);
