import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { graph } from "../lib/agent/graph";

/**
 * The agent's shape, read off the compiled graph rather than drawn.
 *
 * The page has claimed a routed graph with conditional edges since it was built,
 * and the only evidence for that claim was an ASCII diagram in a comment, which
 * is a picture of an intention. LangGraph compiles the real thing and can be
 * asked what it compiled, so that is what ships: if an edge is added, removed,
 * or stops being conditional, the figure on the page changes on the next build
 * without anyone editing it.
 *
 * The distinction that matters to a reader is conditional versus unconditional.
 * A graph whose edges are all unconditional is a pipeline with extra vocabulary;
 * the two conditional edges out of `route` are the entire reason this is a graph
 * at all, and they are why a compensation question never reaches a model.
 */
type Edge = { source: string; target: string; conditional?: boolean };

async function main() {
const drawn = await (graph as unknown as {
  getGraphAsync: (c: Record<string, unknown>) => Promise<{
    nodes: Record<string, unknown>;
    edges: Edge[];
  }>;
}).getGraphAsync({});

// LangGraph names the entry and exit nodes with reserved double-underscore ids.
// Rendered as start and end, because the internal spelling is noise to a reader.
const pretty = (id: string) => id.replace(/^__(start|end)__$/, "$1");

const nodes = Object.keys(drawn.nodes).map(pretty);
const edges = drawn.edges.map((e) => ({
  from: pretty(e.source),
  to: pretty(e.target),
  conditional: Boolean(e.conditional),
}));

const out = {
  note: "Generated by scripts/build-topology.ts from the compiled graph. Do not edit by hand.",
  nodes,
  edges: edges.sort((a, b) => a.from.localeCompare(b.from) || a.to.localeCompare(b.to)),
  conditional: edges.filter((e) => e.conditional).length,
};

writeFileSync(join(process.cwd(), "lib/agent/topology.json"), JSON.stringify(out, null, 2) + "\n");
console.log(
  `build-topology: ${nodes.length} nodes, ${edges.length} edges, ${out.conditional} conditional`,
);
}

main();
