import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Projects the retrieval corpus into three dimensions, honestly.
 *
 * The field this feeds is the one place on the page where the visual and the
 * claim are the same object, so the projection has to be defensible rather than
 * merely attractive.
 *
 * Why classical MDS and not UMAP or t-SNE, which is what everyone reaches for:
 * this corpus is 16 chunks. UMAP's default n_neighbors is 15, so a neighbourhood
 * would be almost the entire dataset and estimating local structure is
 * meaningless. t-SNE is worse here: on identical data, perplexity 10, 30 and 50
 * produce 15, 8 and 3 apparent clusters, and neighbour-embedding methods are
 * documented to render clusters that do not exist. Either one would have put
 * points on screen whose positions were an artifact of a hyperparameter, on a
 * page whose first rule is that a claim the reader cannot check is a bug.
 *
 * At n=16 every pairwise distance is already known exactly, so there is nothing
 * to estimate. Classical MDS takes the full 16x16 cosine distance matrix and
 * finds the 3D configuration minimising distortion against it. Deterministic,
 * no tuning knob, and it degrades honestly: whatever it cannot preserve shows up
 * in the stress number rather than being hidden.
 *
 * That number ships with the data and is rendered beside the field. A projection
 * that publishes its own distortion is the difference between a visualisation
 * and a decoration.
 */

type Index = {
  passages: { parent: string }[];
  parents: { title: string; source: string }[];
  vectors: number[][] | null;
};

const ROOT = process.cwd();
const index = JSON.parse(
  readFileSync(join(ROOT, "lib/agent/index.json"), "utf8"),
) as Index;

const { passages, parents, vectors: passageVectors } = index;

/*
 * One vector per section, not per passage.
 *
 * index.json holds a vector per passage (62 at last count, retrieval's
 * granularity), but the live retrieval trace this figure has to match
 * reports one row per section (lib/agent/retrieve.ts:435, idx.parents.map),
 * eighteen of them. Projecting at passage granularity would draw a
 * different point count at rest than the figure redraws to once a question
 * is asked. Mean-pooling each section's passage vectors is the same
 * reduction the rest of the pipeline already applies to go from passage to
 * section, and it is deterministic, so the committed coordinates do not
 * depend on which passage happened to embed most centrally.
 */
const chunks = parents;
const vectors = passageVectors
  ? parents.map((parent) => {
      const members = passages
        .map((p, i) => (p.parent === parent.title ? passageVectors[i] : null))
        .filter((v): v is number[] => v !== null);
      const dims = members[0]?.length ?? 0;
      const mean = new Array(dims).fill(0);
      for (const v of members) for (let d = 0; d < dims; d++) mean[d] += v[d] / members.length;
      return mean;
    })
  : null;

/**
 * No vectors means no projection, and that is a supported state rather than a
 * crash.
 *
 * `build-index` falls back to a lexical-only index whenever the embedding key is
 * absent, which is exactly what happens in CI: no secret, no vectors, and this
 * script used to read `.length` off null and take the whole build down with it.
 * That broke the rule the rest of the repo is built on, which is that a missing
 * key degrades rather than fails.
 *
 * The figure does not actually need this file to draw a run. Ranks come from the
 * live retrieval trace; all field.json supplies is the resting order and the
 * honesty note about the projection. So without vectors it emits the chunk list
 * and a null stress, and the component omits the line it can no longer support.
 */
if (!vectors) {
  const out = {
    note: "Generated by scripts/build-field.ts. No embedding key at build time, so no projection was computed.",
    method: "lexical-only" as const,
    n: chunks.length,
    dims: 0,
    stress: null,
    eigenvalues: [] as number[],
    points: chunks.map((c) => ({ title: c.title, source: c.source, p: [0, 0, 0] })),
    neighbours: chunks.map(() => -1),
  };
  writeFileSync(join(ROOT, "lib/agent/field.json"), JSON.stringify(out, null, 2) + "\n");
  console.log(
    `build-field: ${chunks.length} points, no vectors available, projection skipped`,
  );
  process.exit(0);
}

const n = vectors.length;

/** Cosine distance. Vectors are already unit length from the embedder, but the
 *  norm is computed anyway so this stays correct if that ever changes. */
function cosineDistance(a: number[], b: number[]): number {
  let dot = 0;
  let na = 0;
  let nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na += a[i] * a[i];
    nb += b[i] * b[i];
  }
  const denom = Math.sqrt(na) * Math.sqrt(nb);
  return denom === 0 ? 1 : 1 - dot / denom;
}

// The full distance matrix. 120 unique pairs at n=16, all of them real.
const D: number[][] = Array.from({ length: n }, (_, i) =>
  Array.from({ length: n }, (_, j) => (i === j ? 0 : cosineDistance(vectors[i], vectors[j]))),
);

/**
 * Classical MDS via double centring and eigendecomposition of the Gram matrix.
 *
 * B = -1/2 * J * D^2 * J, then the top 3 eigenpairs give coordinates. Power
 * iteration with deflation is used rather than a full eigensolver: three
 * components of a 16x16 symmetric matrix does not justify a linear algebra
 * dependency, and this converges in milliseconds.
 */
function classicalMDS(D: number[][], dims = 3) {
  const n = D.length;

  // Double centring.
  const sq = D.map((row) => row.map((d) => d * d));
  const rowMean = sq.map((r) => r.reduce((a, b) => a + b, 0) / n);
  const grand = rowMean.reduce((a, b) => a + b, 0) / n;
  const B = sq.map((row, i) =>
    row.map((v, j) => -0.5 * (v - rowMean[i] - rowMean[j] + grand)),
  );

  const coords: number[][] = Array.from({ length: n }, () => new Array(dims).fill(0));
  const eigenvalues: number[] = [];
  // Taken before deflation, which mutates `work` in place.
  const trace = B.reduce((sum, row, i) => sum + row[i], 0);
  const work = B.map((r) => [...r]);

  for (let d = 0; d < dims; d++) {
    // Deterministic start vector, so the build output is reproducible. A random
    // seed here would mean the committed coordinates changed on every run.
    let v = Array.from({ length: n }, (_, i) => Math.cos((i + 1) * (d + 1)));
    let lambda = 0;

    for (let iter = 0; iter < 512; iter++) {
      const next = work.map((row) => row.reduce((s, x, j) => s + x * v[j], 0));
      const norm = Math.hypot(...next);
      if (norm < 1e-12) break;
      const normalised = next.map((x) => x / norm);
      const delta = normalised.reduce((s, x, i) => s + Math.abs(x - v[i]), 0);
      v = normalised;
      lambda = norm;
      if (delta < 1e-11) break;
    }

    eigenvalues.push(lambda);
    // Negative eigenvalues mean the distance matrix is not Euclidean-embeddable
    // in this many dimensions. Clamping to 0 is the standard treatment and the
    // shortfall surfaces in stress rather than being papered over.
    const scale = Math.sqrt(Math.max(lambda, 0));
    for (let i = 0; i < n; i++) coords[i][d] = v[i] * scale;

    // Deflate so the next iteration finds the following component.
    for (let i = 0; i < n; i++) {
      for (let j = 0; j < n; j++) work[i][j] -= lambda * v[i] * v[j];
    }
  }

  /*
   * Total variance, so the share the projection keeps can be computed rather
   * than asserted.
   *
   * The page has claimed "only 47% of variance in three axes" as a hardcoded
   * string while the eigenvalues sat unread beside it, and the top three alone
   * cannot produce that ratio -- the denominator is the total. For classical
   * MDS the trace of the double-centred Gram matrix is exactly that total, so
   * it is taken before deflation touches the working copy.
   */
  return { coords, eigenvalues, trace };
}

const { coords, eigenvalues, trace } = classicalMDS(D, 3);

/**
 * Kruskal stress-1: sqrt( sum (d_true - d_proj)^2 / sum d_true^2 ).
 *
 * Convention, so the rendered number can be read: under 0.05 excellent, 0.05 to
 * 0.10 good, 0.10 to 0.20 fair, above 0.20 poor. Reported as measured, whatever
 * it turns out to be.
 */
function kruskalStress(D: number[][], coords: number[][]) {
  let num = 0;
  let den = 0;
  for (let i = 0; i < D.length; i++) {
    for (let j = i + 1; j < D.length; j++) {
      const projected = Math.hypot(
        coords[i][0] - coords[j][0],
        coords[i][1] - coords[j][1],
        coords[i][2] - coords[j][2],
      );
      num += (D[i][j] - projected) ** 2;
      den += D[i][j] ** 2;
    }
  }
  return Math.sqrt(num / den);
}

const stress = kruskalStress(D, coords);

// Normalise into a unit cube so the renderer needs no magic scale constants.
const axes = [0, 1, 2].map((d) => {
  const vals = coords.map((c) => c[d]);
  return { min: Math.min(...vals), max: Math.max(...vals) };
});
const span = Math.max(...axes.map((a) => a.max - a.min)) || 1;
const centre = axes.map((a) => (a.min + a.max) / 2);

const points = coords.map((c, i) => ({
  title: chunks[i].title,
  source: chunks[i].source,
  // Rounded to 4 decimals: below the precision the eye can resolve, and it keeps
  // the committed artifact from churning on floating-point noise between runs.
  p: c.map((v, d) => +(((v - centre[d]) / span) * 2).toFixed(4)),
}));

// Nearest neighbour per point, computed from the TRUE distances rather than the
// projected ones. The field draws these as edges, so they stay correct even
// where the projection distorts.
const neighbours = D.map((row) => {
  let best = -1;
  let bestD = Infinity;
  row.forEach((d, j) => {
    if (d > 0 && d < bestD) {
      bestD = d;
      best = j;
    }
  });
  return best;
});

const out = {
  note: "Generated by scripts/build-field.ts. Classical MDS on the cosine distance matrix. Do not edit by hand.",
  method: "classical-mds",
  n,
  dims: vectors[0].length,
  stress: +stress.toFixed(4),
  eigenvalues: eigenvalues.map((v) => +v.toFixed(4)),
  trace: +trace.toFixed(4),
  // The share of total variance the three plotted axes actually keep. Rendered
  // beside the figure instead of a number typed into a component.
  varianceKept: +(eigenvalues.reduce((a, b) => a + Math.max(b, 0), 0) / trace).toFixed(4),
  points,
  neighbours,
};

writeFileSync(join(ROOT, "lib/agent/field.json"), JSON.stringify(out, null, 2) + "\n");

const quality =
  stress < 0.05 ? "excellent" : stress < 0.1 ? "good" : stress < 0.2 ? "fair" : "poor";
console.log(
  `build-field: ${n} points, ${vectors[0].length}-dim source, ` +
    `Kruskal stress ${stress.toFixed(4)} (${quality})`,
);
