import { writeFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { ask } from "../lib/agent/graph";

/**
 * Answers the opener questions at build time.
 *
 * The three openers are fixed strings and they are what most visitors click, so
 * paying two to four seconds of model latency for them at request time is a cost
 * with no upside. Answering them during the build makes the first thing a visitor
 * does instant, and leaves the streaming path for questions that are genuinely
 * unpredictable.
 *
 * Regenerated on every build, so a change to the corpus changes these too. If a
 * question fails here the entry is skipped rather than baked wrong, and it falls
 * through to the live path.
 */
const OPENERS = [
  "What has he shipped on Azure?",
  "What broke in production and how did he find it?",
  // Must match Agent.tsx OPENERS exactly. It did not: the agent offered
  // "How does he know the retrieval is actually working?" and this baked an
  // answer to a different question, so the third opener paid a full model round
  // trip on every click while a warm answer nobody could reach sat in the
  // bundle.
  "How does he know the retrieval is actually working?",
];

/**
 * Files whose contents decide what a baked answer says.
 *
 * A cached answer outlives the code that produced it, silently. Every entry in
 * prewarm.json was generated by whatever prompt and provider config were on
 * disk at the time, and nothing checked afterwards -- so when reasoning was
 * switched off at the provider and the system prompt changed underneath it, the
 * three questions most visitors click would have kept serving answers written
 * by the old configuration, complete with whatever it used to leak.
 *
 * Cheapest honest check available: if any of these is newer than the bake, the
 * bake is stale. It costs a stat call and it catches the whole class.
 */
const SOURCES = [
  "lib/agent/policy.ts",
  "lib/agent/model.ts",
  "lib/agent/retrieve.ts",
  "lib/agent/index.json",
];

/** Throws when the baked answers are older than the code that writes them. */
export function assertFresh(bakedAt: number) {
  const stale = SOURCES.filter((f) => {
    try {
      return statSync(join(process.cwd(), f)).mtimeMs > bakedAt;
    } catch {
      return false;
    }
  });
  if (stale.length) {
    throw new Error(
      `prewarm.json is older than ${stale.join(", ")}.\n` +
        `  The baked openers were written by a different prompt or provider config.\n` +
        `  Run \`npm run prewarm\` before building.`,
    );
  }
}

async function main() {
  const warm: Record<string, unknown> = {};

  for (const question of OPENERS) {
    try {
      const result = await ask(question);
      if (result.answer && result.route === "answer") {
        warm[question.toLowerCase().trim()] = result;
        console.log(`prewarm: ${result.total}ms  ${question}`);
      }
    } catch {
      console.log(`prewarm: skipped  ${question}`);
    }
  }

  const out = join(process.cwd(), "lib", "agent", "prewarm.json");
  writeFileSync(out, JSON.stringify(warm, null, 2));
  console.log(`prewarm: ${Object.keys(warm).length} of ${OPENERS.length} baked`);

  // Proves the check passes on a bake that just happened, so a broken clock or
  // a wrong path surfaces here rather than as a build failure nobody can
  // reproduce.
  assertFresh(Date.now());
}

main();
