import { streamWithFailover, listPrice, failoverState, chooseTool } from "./model";
import {
  toolSchemas,
  openEvidence,
  composeIntro,
  runEval,
  EVAL_SESSION_CAP,
  type ToolResult,
} from "./tools";
import type { RetrievalTrace } from "./retrieve";
import { retrieve } from "./retrieve";
import {
  classify,
  systemPrompt,
  cleanAnswer,
  deflection,
  handoffAnswer,
  AUTHORISATION_ANSWER,
  POLICY_PREVIEW,
} from "./policy";
import { analyze } from "./query";
import { offersFor } from "./followups";
import type { Offer } from "./offers";
import { loadContent } from "../content";
import prewarm from "./prewarm.json";

/** Named once so the tool prompt says who it is acting for. */
const OWNER = loadContent().profile.name;

/**
 * Streaming path for the agent.
 *
 * The non-streaming graph stays as it is: it backs the evals and the hero's
 * measured trace, where a single settled answer is what gets asserted against.
 * This runs the same three stages for a visitor who is waiting, and emits each
 * one as it completes so text appears while the model is still producing it.
 *
 * Server-Sent Events rather than a socket. The traffic is one-directional and
 * request-scoped, so a persistent connection would add reconnect handling and
 * an idle timeout on serverless hosting to solve a problem this shape does not
 * have. EventSource also reconnects on its own, which a raw socket does not.
 */
export type StreamEvent =
  | { type: "route"; route: string; ms: number }
  | { type: "sources"; titles: string[]; ms: number; trace?: RetrievalTrace }
  | { type: "token"; text: string }
  /**
   * What the reader can do next, computed from the sections that were actually
   * retrieved rather than generated by the model.
   *
   * Sent as its own event after the answer settles. A model asked to suggest
   * follow-ups also suggests questions the corpus cannot answer, and a
   * suggestion that leads to "that is outside what I cover" costs more trust
   * than offering nothing at all. Every `open` here is a URL the build's link
   * checker resolved; every `ask` is a question written beside the section that
   * answers it.
   */
  | { type: "offers"; offers: Offer[] }
  /**
   * Something the agent did, rather than said.
   *
   * Carries a typed result so the client renders an affordance rather than
   * parsing prose. A failed tool arrives here too, as `ok: false` with the
   * sentence a reader gets -- the failure is an answer, never a broken control.
   */
  | { type: "action"; result: ToolResult }
  | {
      type: "done";
      total: number;
      usage: { in: number; out: number } | null;
      /** Which provider actually produced the tokens, and on what model. */
      provider?: string | null;
      model?: string | null;
      /** What the same tokens cost at that model's published list rate. */
      listPrice?: number | null;
      /** Providers currently benched by a rate limit, with seconds remaining. */
      failover?: { name: string; coolingOffFor: number }[];
      /** True when the turn was answered from the build-time cache. */
      warm?: boolean;
      /** True when no provider was reachable and the retrieved source was
       *  served unsummarised instead of failing. */
      degraded?: boolean;
      /** The system prompt, context elided. Shown on request in the trace. */
      policy?: string;
    }
  | { type: "error"; message: string };

/**
 * What the prewarm script actually stored.
 *
 * It writes the whole result of a real run -- route, per-node timings, total,
 * token usage, the provider that served it and the full retrieval trace -- and
 * this type declared three of those fields and read two. So a cached answer
 * arrived with no timings, no tokens, no cost and no provider, and the trace
 * panel under it was empty on exactly the three questions most visitors click.
 * All of it was measured at build time and thrown away at serve time.
 */
type Warm = Record<
  string,
  {
    answer: string;
    route: string;
    sources: string[];
    timings: Record<string, number>;
    total: number;
    usage: { in: number; out: number } | null;
    provider: string | null;
    trace?: RetrievalTrace;
  }
>;

/**
 * What was already said in this conversation.
 *
 * The graph's own comment claimed "conversation history is passed in per
 * request instead", and it was not: nothing accepted history, so every
 * follow-up was answered as if it were the first thing anyone had asked. A
 * reader who asked "what did he do at IMG Systems" and then "why did he do it
 * that way" got a generic answer to the second question, which reads exactly
 * like a page that does not know what it is talking about.
 *
 * Held in the browser tab and sent per request, which is the design the
 * checkpointer decision assumed. Bounded to the last two exchanges: enough to
 * resolve "it", "that" and "why", short enough that the prompt does not grow
 * without limit on a public endpoint someone else is paying for.
 */
export type Exchange = { question: string; answer: string };

const HISTORY_TURNS = 2;
const HISTORY_ANSWER_CHARS = 400;

function historyMessages(history: Exchange[]) {
  return history.slice(-HISTORY_TURNS).flatMap((h) => [
    { role: "user", content: h.question },
    { role: "assistant", content: h.answer.slice(0, HISTORY_ANSWER_CHARS) },
  ]);
}

/**
 * Retrieval sees the conversation too, not just the latest question.
 *
 * "Why did he do it that way" has no retrievable terms of its own. Searching
 * the corpus for it returns whatever is generically closest, which is how a
 * follow-up ended up grounded in the wrong section. Prepending the previous
 * question puts the subject back into the query without letting an old topic
 * outweigh the new one.
 */
function retrievalQuery(question: string, history: Exchange[]) {
  // The question is classified and expanded before the previous turn is
  // prepended, so a follow-up to an identity or work question keeps the
  // vocabulary that made the first one retrievable.
  const { intent, query, weight, asked, floor } = analyze(question);
  const previous = history.at(-1)?.question;
  return { intent, weight, asked, floor, query: previous ? `${previous} ${query}` : query };
}

export async function* runStream(
  question: string,
  history: Exchange[] = [],
): AsyncGenerator<StreamEvent> {
  const started = Date.now();

  // Openers were answered at build time. Serving them from the bundle costs a
  // map lookup instead of an embedding call plus a model round trip, which is
  // the difference between an instant demo and a three second wait on the one
  // interaction most visitors have.
  // Only on a first turn. A cached answer cannot take the conversation into
  // account, and serving one mid-thread is how a follow-up gets answered with
  // the opener's reply.
  const warm = history.length === 0 ? (prewarm as unknown as Warm)[question.toLowerCase().trim()] : undefined;
  if (warm) {
    // The timings are the ones the real run measured, not zeroes. A cached
    // answer is still an answer something produced; reporting it as costless
    // and instantaneous would be the page's only dishonest number.
    yield { type: "route", route: warm.route ?? "answer", ms: warm.timings?.route ?? 0 };
    yield {
      type: "sources",
      titles: warm.sources,
      ms: warm.timings?.retrieve ?? 0,
      trace: warm.trace,
    };
    yield { type: "token", text: warm.answer };
    // Recomputed rather than baked. The offers depend on the corpus, which can
    // change under a cached answer, and an offer pointing at an artifact that
    // has since been removed is exactly the class of stale claim the freshness
    // gate on this file exists to stop.
    yield {
      type: "offers",
      offers: offersFor(warm.sources.map((title) => ({ title, body: "", source: "facts" }))),
    };
    // Flagged rather than served silently. A zero-millisecond answer with no
    // explanation reads as a canned script, which is the exact opposite of what
    // this box is trying to demonstrate; labelled, it reads as a cache.
    yield {
      type: "done",
      total: warm.total ?? Date.now() - started,
      usage: warm.usage ?? null,
      provider: warm.provider ?? null,
      model: null,
      listPrice: null,
      failover: failoverState(),
      warm: true,
      policy: POLICY_PREVIEW,
    };
    return;
  }

  const route = classify(question);
  yield { type: "route", route, ms: Date.now() - started };

  /*
   * An instruction, not a question.
   *
   * "Pull up his LinkedIn" is answered by doing it. There is no corpus in this
   * call and no second turn: the model picks one action, it is executed, and
   * the result is rendered. Nothing is fed back for another opinion, so the
   * retry loop that dominates production tool-use failures has nowhere to
   * happen, and the ordinary answer path never carries tool schemas it will
   * not use.
   */
  if (route === "act") {
    yield { type: "sources", titles: [], ms: 0 };
    const chosen = await chooseTool(
      [
        {
          role: "system",
          content:
            `You act on behalf of a visitor reading ${OWNER}'s portfolio. ` +
            `Call exactly one tool for what they asked. Never call more than one.`,
        },
        ...historyMessages(history),
        { role: "user", content: question },
      ],
      toolSchemas(),
    );

    const call = chosen?.calls[0];
    let result: ToolResult;

    if (!call) {
      // No provider, or the model declined. Both mean the same thing to a
      // reader: say what can be done rather than failing silently.
      result = {
        ok: false,
        say: `I can open his LinkedIn, his GitHub, the source for this page, the LangChain issue and its merged fix, or either publication. I can also draft an email to him, or run one of this site's own eval cases.`,
      };
    } else if (call.name === "open_evidence") {
      result = openEvidence(String(call.args.target ?? ""));
    } else if (call.name === "compose_intro") {
      result = composeIntro(String(call.args.about ?? "general"));
    } else if (call.name === "run_eval") {
      // Capped per conversation. Each case is a real model call on a free tier
      // shared with the next visitor, and a reader who finds the button
      // entertaining should not be able to spend the day's budget on it.
      const used = history.filter((h) => /Ran it just now/.test(h.answer)).length;
      result =
        used >= EVAL_SESSION_CAP
          ? {
              ok: false,
              say: `That is ${EVAL_SESSION_CAP} demonstrations this session, which is the cap. The whole suite runs on every deploy and the result is on this page.`,
            }
          : await runEval(String(call.args.about ?? "grounding"), async (q) => {
              const { ask } = await import("./graph");
              const r = await ask(q);
              return { answer: r.answer, route: r.route };
            });
    } else {
      result = { ok: false, say: `That is not something this page can do.` };
    }

    yield { type: "token", text: result.say };
    yield { type: "action", result };
    yield {
      type: "done",
      total: Date.now() - started,
      usage: null,
      provider: chosen?.provider ?? null,
      failover: failoverState(),
      policy: POLICY_PREVIEW,
    };
    return;
  }

  // Deflections and the authorisation answer are fixed text. Streaming them a
  // character at a time would fake latency that is not there.
  if (route !== "answer" && route !== "handoff") {
    const text = route === "authorisation" ? AUTHORISATION_ANSWER : deflection(question);
    yield { type: "sources", titles: [], ms: 0 };
    yield { type: "token", text };
    // No provider is named here because none was called. That is the point of
    // the deflection path and the trace should show it rather than imply a model
    // considered the question and declined.
    yield { type: "done", total: Date.now() - started, usage: null, policy: POLICY_PREVIEW };
    return;
  }

  const retrieveStart = Date.now();
  const { intent, query, weight, asked, floor } = retrievalQuery(question, history);
  const { chunks, trace } = await retrieve(query, 4, weight, floor);
  yield {
    type: "sources",
    titles: chunks.map((c) => c.title),
    ms: Date.now() - retrieveStart,
    // The full fusion, every chunk, so the page can draw what actually
    // happened rather than an illustration of it.
    trace,
  };

  const context = chunks.map((c) => `## ${c.title}\n${c.body}`).join("\n\n");

  try {
    /**
     * Nothing is held back any more, because nothing arrives that needs holding.
     *
     * This used to buffer the opening of every answer: 48 characters, or a
     * paragraph break, whichever came first, and `looksLikeReasoning` decided
     * whether the tokens so far were an answer or a model narrating its own
     * instructions. It was necessary. A token already painted cannot be
     * unpainted, and a leaked monologue costs more than a delay.
     *
     * It is now dead weight. The provider is told not to produce reasoning at
     * all -- see the measurement in model.ts -- so the buffer was spending
     * time-to-first-token on a case that can no longer happen. Measured against
     * the streaming endpoint with reasoning off: first token at 275ms.
     *
     * cleanAnswer still runs on every emit and on the settled buffer. It is a
     * net under the fix rather than the fix, which is the correct shape for it
     * and the shape it was originally given: the provider is configurable, and
     * the next one may not honour the flag.
     */
    let buffer = "";
    let emitted = 0;
    let usage: { in: number; out: number } | null = null;
    let served: { provider: string; model: string } | null = null;

    for await (const token of streamWithFailover(
      [
        { role: "system", content: systemPrompt(context) },
        ...historyMessages(history),
        // `asked` rather than `question`: an identity question is addressed to
        // the assistant, and a model that reads "yourself" answers as him
        // however many times the system prompt says third person.
        { role: "user", content: asked },
      ],
      (u) => {
        usage = u;
      },
      (provider, model) => {
        served = { provider, model };
      },
    )) {
      buffer += token;

      // The one case a post-hoc clean cannot cover.
      //
      // An open <think> block is reasoning by definition and a token already
      // sent cannot be recalled, so the stream waits for the closing tag. This
      // is free on a normal answer -- the test fails on the first character and
      // nothing is delayed -- and it is the whole of what the old 48-character
      // buffer is still needed for now that the provider is told not to reason
      // at all. It exists for a provider that ignores the flag, which the
      // env-configurable model id makes possible.
      if (/<think>/i.test(buffer) && !/<\/think>/i.test(buffer)) continue;

      const clean = cleanAnswer(buffer, intent === "limitation");
      if (clean.length > emitted) {
        yield { type: "token", text: clean.slice(emitted) };
        emitted = clean.length;
      }
    }

    // A short answer that never reached the release threshold still has to be
    // sent. Cleaned first, because this is the path a fully-buffered reply from
    // a non-streaming provider takes.
    //
    // The handoff close is appended here rather than mid-stream. `classify`
    // routes a hiring question to `handoff` and the non-streaming graph calls
    // handoffAnswer() on it, but this path let `handoff` fall through to the
    // ordinary answer branch -- so the one line written for the reader who is
    // actually asking about a role ("He is talking to teams for January 2027",
    // with his address) has never reached a visitor. Every visitor uses this
    // path; nothing but the eval suite uses the other one.
    const cleaned = cleanAnswer(buffer, intent === "limitation");
    const final = route === "handoff" ? handoffAnswer(cleaned) : cleaned;
    if (final.length > emitted) {
      yield { type: "token", text: final.slice(emitted) };
      emitted = final.length;
    }

    yield { type: "offers", offers: offersFor(chunks) };

    const settled = served as { provider: string; model: string } | null;
    yield {
      type: "done",
      total: Date.now() - started,
      usage,
      provider: settled?.provider ?? null,
      model: settled?.model ?? null,
      listPrice: usage && settled ? listPrice(settled.model, usage) : null,
      failover: failoverState(),
      policy: POLICY_PREVIEW,
    };
  } catch {
    /**
     * Every provider is down, and the answer degrades rather than erroring.
     *
     * The corpus has claimed exactly this since the site was built -- "with no
     * provider reachable, the agent returns the retrieved source paragraph
     * instead of a failure" -- and it was true of the non-streaming graph, which
     * backs the evals, and false of the streaming path, which is the only one a
     * visitor ever touches. So the page described a degradation it did not
     * perform, and the reader who hit it got "The model is unavailable" on a
     * page whose whole argument is that it stays useful when things break.
     *
     * The retrieval already succeeded; only the summarising failed. Serving the
     * top chunk unsummarised gives the reader the grounded material and says
     * plainly that it is unsummarised, which is worth more than an apology.
     */
    const grounded = chunks[0]?.body.split("\n\n").find((p) => p.trim().length > 0);

    if (grounded) {
      yield {
        type: "token",
        text: `${grounded.replace(/\*\*/g, "")}\n\nThat is the source text, unsummarised: every model provider is rate-limited right now. Retrieval still ran, and the sources above are the ones it chose.`,
      };
      yield { type: "offers", offers: offersFor(chunks) };
      yield {
        type: "done",
        total: Date.now() - started,
        usage: null,
        degraded: true,
        failover: failoverState(),
        policy: POLICY_PREVIEW,
      };
      return;
    }

    yield { type: "error", message: "The model is unavailable. Reach him directly by email." };
  }
}
